"""
Card Rater — interactive digest card rating
============================================
Displays cards generated by generate_digests.py and collects
your usefulness rating per persona.

Usage:
  uv run rate

Controls:
  1-5  → rating (1=useless, 5=excellent)
  s    → skip card
  q    → save and quit

Output:
  ratings/ratings.json   ← raw ratings
  ratings/feedback.json  ← ready input for score_feedback.py
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT        = Path(__file__).parent.parent
DIGESTS_DIR = ROOT / "artifacts" / "digests"
RATINGS_DIR = ROOT / "artifacts" / "ratings"

# ── Persona descriptions — shown during rating ────────────────────────────────

PERSONAS = {
    "alex": {
        "name":        "Alex — Senior ML Engineer",
        "description": (
            "Wants to know: does it work in production, what are the benchmarks, "
            "is there code, what does it replace, latency and cost. "
            "Skips hype, funding, and org changes."
        ),
        "color": "\033[94m",   # blue
    },
    "jordan": {
        "name":        "Jordan — VP of Engineering",
        "description": (
            "Wants to know: is it mature, who is winning, what to prioritize this quarter. "
            "Does not need implementation details or code."
        ),
        "color": "\033[92m",   # green
    },
}

# ── Terminal helpers ──────────────────────────────────────────────────────────

RESET  = "\033[0m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
YELLOW = "\033[93m"
RED    = "\033[91m"


def clear():
    os.system("cls" if os.name == "nt" else "clear")


def hr(char: str = "─", width: int = 62) -> str:
    return char * width


def print_card(card: dict, index: int, total: int, snapshot_label: str):
    """Displays a card in a readable format."""
    print(f"\n{hr('═')}")
    print(f"{BOLD}Card {index}/{total}{RESET}  {DIM}{snapshot_label}{RESET}")
    print(hr())

    # Fields in priority order
    priority_fields = ["TITLE", "ARXIV_ID", "GITHUB_URL", "BENCHMARK",
                       "RESULT", "REPLACES", "HARDWARE", "LICENSE", "VERDICT",
                       "MATURITY", "COMPETITOR", "EFFORT", "RECOMMENDATION", "RATIONALE"]

    for field in priority_fields:
        val = None
        for k, v in card.items():
            if k.upper() == field:
                val = v
                break
        if val and val not in ("N/A", "n/a", ""):
            label = f"{field}:"
            print(f"  {BOLD}{label:<16}{RESET} {val}")

    # Any remaining fields not in the priority list
    shown = {f.upper() for f in priority_fields}
    for k, v in card.items():
        if k.upper() not in shown and v and v not in ("N/A", ""):
            print(f"  {DIM}{k:<16}{RESET} {v}")

    print(hr())


def ask_rating(persona_key: str) -> int | None:
    """
    Prompts for a rating for the given persona.
    Returns 1-5, None if skipped, or raises SystemExit if quit.
    """
    p = PERSONAS[persona_key]
    color = p["color"]

    print(f"\n{color}{BOLD}{p['name']}{RESET}")
    print(f"{DIM}{p['description']}{RESET}")
    print(f"\n  How useful is this card for {p['name'].split(' — ')[0]}?")
    print(f"  {BOLD}1{RESET} = useless  "
          f"{BOLD}2{RESET} = poor  "
          f"{BOLD}3{RESET} = OK  "
          f"{BOLD}4{RESET} = good  "
          f"{BOLD}5{RESET} = excellent")
    print(f"  {DIM}[s] skip  [q] save and quit{RESET}\n")

    while True:
        try:
            raw = input("  Rating: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\n\nInterrupted — saving progress...")
            raise SystemExit(0)

        if raw == "q":
            raise SystemExit(0)
        if raw == "s":
            return None
        if raw in ("1", "2", "3", "4", "5"):
            return int(raw)
        print(f"  {RED}Enter 1-5, s, or q.{RESET}")


# ── Load all cards ────────────────────────────────────────────────────────────

def load_all_cards() -> list[dict]:
    """
    Loads cards from all digests.
    Deduplicates by title — the same card may appear in both the alex
    and jordan digests for the same snapshot.
    """
    digest_files = sorted(DIGESTS_DIR.glob("snapshot_*.json"))
    if not digest_files:
        print(f"✗  No digests found in {DIGESTS_DIR}/")
        print("   Run first: uv run gen-digests")
        sys.exit(1)

    cards_by_title: dict[str, dict] = {}

    for path in digest_files:
        digest  = json.loads(path.read_text())
        snap_id = digest["snapshot_id"]
        label   = digest["label"]

        for card in digest.get("cards", []):
            title = (
                card.get("TITLE") or
                card.get("title") or
                "untitled"
            ).strip()[:80]

            key = f"{snap_id}::{title.lower()}"

            if key not in cards_by_title:
                cards_by_title[key] = {
                    "key":           key,
                    "snapshot_id":   snap_id,
                    "label":         label,
                    "title":         title,
                    "card":          card,
                    "rating_alex":   None,
                    "rating_jordan": None,
                    "skipped":       False,
                }

    return list(cards_by_title.values())


def load_existing_ratings() -> dict[str, dict]:
    """Loads existing ratings so a session can be resumed."""
    path = RATINGS_DIR / "ratings.json"
    if path.exists():
        data = json.loads(path.read_text())
        return {r["key"]: r for r in data}
    return {}


def save_ratings(cards: list[dict]):
    RATINGS_DIR.mkdir(exist_ok=True)
    path = RATINGS_DIR / "ratings.json"
    path.write_text(json.dumps(cards, indent=2, ensure_ascii=False))


def save_feedback(cards: list[dict]):
    """
    Generates feedback.json ready for score_feedback.py
    and as input for the ACE playbook builder.
    """
    rated = [c for c in cards if not c["skipped"] and
             (c["rating_alex"] is not None or c["rating_jordan"] is not None)]

    feedback = {
        "generated_at":   datetime.now(timezone.utc).isoformat(),
        "total_cards":    len(cards),
        "rated_cards":    len(rated),
        "skipped_cards":  sum(1 for c in cards if c["skipped"]),
        "rater":          "human_expert",
        "scale":          "1-5 (1=useless, 5=excellent)",
        "cards": [
            {
                "key":           c["key"],
                "snapshot_id":   c["snapshot_id"],
                "label":         c["label"],
                "title":         c["title"],
                "rating_alex":   c["rating_alex"],
                "rating_jordan": c["rating_jordan"],
                # ACE signals — was the card useful per persona
                "useful_for_alex":   (c["rating_alex"]   or 0) >= 4,
                "useful_for_jordan": (c["rating_jordan"] or 0) >= 4,
                # Cards with large divergence demonstrate why personalization matters
                "divergence": abs(
                    (c["rating_alex"]   or 0) -
                    (c["rating_jordan"] or 0)
                ),
            }
            for c in rated
        ],
    }

    # Summary stats
    alex_ratings   = [c["rating_alex"]   for c in rated if c["rating_alex"]]
    jordan_ratings = [c["rating_jordan"] for c in rated if c["rating_jordan"]]

    if alex_ratings:
        feedback["stats_alex"] = {
            "avg":     round(sum(alex_ratings) / len(alex_ratings), 2),
            "useful":  sum(1 for r in alex_ratings if r >= 4),
            "useless": sum(1 for r in alex_ratings if r <= 2),
        }
    if jordan_ratings:
        feedback["stats_jordan"] = {
            "avg":     round(sum(jordan_ratings) / len(jordan_ratings), 2),
            "useful":  sum(1 for r in jordan_ratings if r >= 4),
            "useless": sum(1 for r in jordan_ratings if r <= 2),
        }

    # Most divergent cards — highlight for the blog post
    divergent = sorted(
        feedback["cards"],
        key=lambda x: x["divergence"],
        reverse=True,
    )[:5]
    feedback["most_divergent_cards"] = divergent

    path = RATINGS_DIR / "feedback.json"
    path.write_text(json.dumps(feedback, indent=2, ensure_ascii=False))
    return feedback


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    clear()
    print(f"\n{BOLD}Card Rater{RESET} — rating cards for Alex and Jordan")
    print(f"{DIM}Data from: {DIGESTS_DIR}/{RESET}\n")

    all_cards = load_all_cards()
    existing  = load_existing_ratings()

    # Restore previous ratings so sessions can be resumed
    restored = 0
    for card in all_cards:
        if card["key"] in existing:
            prev = existing[card["key"]]
            card["rating_alex"]   = prev.get("rating_alex")
            card["rating_jordan"] = prev.get("rating_jordan")
            card["skipped"]       = prev.get("skipped", False)
            restored += 1

    # Only show cards that still need a rating
    to_rate = [
        c for c in all_cards
        if not c["skipped"]
        and (c["rating_alex"] is None or c["rating_jordan"] is None)
    ]

    print(f"  Total cards:    {len(all_cards)}")
    print(f"  Already rated:  {restored}")
    print(f"  To rate now:    {len(to_rate)}")
    print(f"\n  {DIM}You can quit at any time (q) — progress is saved after every card.{RESET}")
    input(f"\n  Press Enter to start...")

    try:
        for i, card in enumerate(to_rate, 1):
            clear()
            print_card(card["card"], i, len(to_rate), card["label"])

            # Rating for Alex
            if card["rating_alex"] is None:
                rating_a = ask_rating("alex")
                if rating_a is None:
                    card["skipped"] = True
                    save_ratings(all_cards)
                    continue
                card["rating_alex"] = rating_a

            # Rating for Jordan
            if card["rating_jordan"] is None:
                rating_j = ask_rating("jordan")
                if rating_j is None:
                    card["skipped"] = True
                    save_ratings(all_cards)
                    continue
                card["rating_jordan"] = rating_j

            # Save after every card — no lost progress on interrupt
            save_ratings(all_cards)

            a    = card["rating_alex"]
            j    = card["rating_jordan"]
            diff = abs(a - j)
            diff_label = (
                f"{YELLOW}↑ large divergence ({diff} pts) — interesting for the blog!{RESET}"
                if diff >= 2 else ""
            )
            print(f"\n  {DIM}Alex: {a}/5  Jordan: {j}/5  {diff_label}{RESET}")
            input(f"  {DIM}Enter → next card...{RESET}")

    except SystemExit:
        pass

    # Final stats and save
    clear()
    feedback = save_feedback(all_cards)

    rated = feedback["rated_cards"]
    print(f"\n{BOLD}Done!{RESET}\n")
    print(f"  Cards rated:  {rated}/{len(all_cards)}")

    if "stats_alex" in feedback:
        s = feedback["stats_alex"]
        print(f"\n  {PERSONAS['alex']['color']}{BOLD}Alex{RESET}")
        print(f"    Average:  {s['avg']}/5")
        print(f"    Useful:   {s['useful']} cards (≥4)")
        print(f"    Poor:     {s['useless']} cards (≤2)")

    if "stats_jordan" in feedback:
        s = feedback["stats_jordan"]
        print(f"\n  {PERSONAS['jordan']['color']}{BOLD}Jordan{RESET}")
        print(f"    Average:  {s['avg']}/5")
        print(f"    Useful:   {s['useful']} cards (≥4)")
        print(f"    Poor:     {s['useless']} cards (≤2)")

    if feedback.get("most_divergent_cards"):
        print(f"\n  {YELLOW}{BOLD}Most divergent cards (gold for the blog):{RESET}")
        for c in feedback["most_divergent_cards"][:3]:
            print(f"    [{c['divergence']} pt gap] {c['title'][:55]}")

    print(f"\n  Files:")
    print(f"    ratings/ratings.json  — raw ratings")
    print(f"    ratings/feedback.json — input for uv run score\n")


if __name__ == "__main__":
    main()
